name: Simple GitHub Actions Workflow for Java Application

#on: [push]

on: 
  push:
  schedule: 
    - cron: "* * * * *"
# pull_request: 
#   types: [closed, assigned, opened, reopened]


jobs:
  run-gihub-actions:
    runs-on: ubuntu-latest
    steps: 
     - name: Hello World Action
       id: hello
       uses: actions/hello-world-javascript-action@master

       with:
         who-to-greet: devopshint

     - name: Get the output time
       run: echo "${{ steps.hello.outputs.time }}"
